import { Client, Appointment, FinancialTransaction, ClinicSettings, ServiceCategory, Service } from '../types';

export const DEFAULT_SETTINGS: ClinicSettings = {
  clinicName: 'CK Próteses Capilares',
  googleClientId: '',
  calendarId: 'primary',
  enableGoogleCalendar: false,
  theme: 'light',
};

// Generates some dates relative to today for mock consistency
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const SEED_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Roberto Alves de Souza',
    phone: '(11) 98765-4321',
    email: 'roberto.alves@email.com',
    notes: 'Prótese de micropele 0.08mm. Realiza manutenção a cada 3 semanas. Prefere adesão total com cola Ultra Hold.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    name: 'Cláudio Ferreira Lima',
    phone: '(11) 91234-5678',
    email: 'claudio.lima@gmail.com',
    notes: 'Prótese híbrida (centro micropele, bordas em tela/lace). Sensibilidade a álcool isopropílico, utilizar removedor cítrico.',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    name: 'Felipe Augusto Melo',
    phone: '(21) 99887-7665',
    email: 'felipe.melo@hotmail.com',
    notes: 'Cliente exigente. Realiza corte e manutenção de prótese de lace francesa. Prefere fita azul (Walker Tape) no contorno.',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c4',
    name: 'Ricardo de Oliveira',
    phone: '(11) 95555-4444',
    email: 'ricardo.oliveira@outlook.com',
    notes: 'Novo cliente. Fez avaliação e adquiriu a primeira prótese premium sob medida de cabelo humano.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_APPOINTMENTS: Appointment[] = [
  // Past appointments
  {
    id: 'a1',
    clientId: 'c1',
    clientName: 'Roberto Alves de Souza',
    clientPhone: '(11) 98765-4321',
    date: getRelativeDate(-15),
    startTime: '09:00',
    endTime: '10:30',
    serviceName: 'Manutenção Completa (Limpeza e Recolocação)',
    price: 220.00,
    notes: 'Serviço realizado com sucesso. Higienização da prótese e aplicação de nova cola.',
    status: 'Realizado',
    paymentStatus: 'Pago',
    paymentMethod: 'Cartão de Crédito',
    createdAt: getRelativeDate(-15),
  },
  {
    id: 'a2',
    clientId: 'c2',
    clientName: 'Cláudio Ferreira Lima',
    clientPhone: '(11) 91234-5678',
    date: getRelativeDate(-7),
    startTime: '14:00',
    endTime: '15:30',
    serviceName: 'Manutenção e Hidratação de Fios',
    price: 250.00,
    notes: 'Realizado tratamento de hidratação profunda nos fios da prótese para reverter ressecamento.',
    status: 'Realizado',
    paymentStatus: 'Pago',
    paymentMethod: 'Pix',
    createdAt: getRelativeDate(-7),
  },
  {
    id: 'a3',
    clientId: 'c3',
    clientName: 'Felipe Augusto Melo',
    clientPhone: '(21) 99887-7665',
    date: getRelativeDate(-2),
    startTime: '10:00',
    endTime: '11:00',
    serviceName: 'Ajuste de Laterais e Higienização Rápida',
    price: 130.00,
    notes: 'Retoque nas laterais onde a fita descolou. Limpeza rápida.',
    status: 'Realizado',
    paymentStatus: 'Pago',
    paymentMethod: 'Dinheiro',
    createdAt: getRelativeDate(-2),
  },
  // Today's appointments
  {
    id: 'a4',
    clientId: 'c1',
    clientName: 'Roberto Alves de Souza',
    clientPhone: '(11) 98765-4321',
    date: getRelativeDate(0),
    startTime: '09:00',
    endTime: '10:30',
    serviceName: 'Manutenção Completa com Ajuste de Corte',
    price: 240.00,
    notes: 'Cortar um pouco as laterais do cabelo natural para igualar.',
    status: 'Realizado',
    paymentStatus: 'Pago',
    paymentMethod: 'Pix',
    createdAt: getRelativeDate(0),
  },
  {
    id: 'a5',
    clientId: 'c4',
    clientName: 'Ricardo de Oliveira',
    clientPhone: '(11) 95555-4444',
    date: getRelativeDate(0),
    startTime: '14:00',
    endTime: '16:00',
    serviceName: 'Primeira Colocação de Prótese Premium',
    price: 1200.00,
    notes: 'Colocação da prótese sob medida comprada. Realizar corte de integração para acabamento impecável.',
    status: 'Confirmado',
    paymentStatus: 'Pendente',
    createdAt: getRelativeDate(0),
  },
  // Future appointments
  {
    id: 'a6',
    clientId: 'c2',
    clientName: 'Cláudio Ferreira Lima',
    clientPhone: '(11) 91234-5678',
    date: getRelativeDate(2),
    startTime: '11:00',
    endTime: '12:30',
    serviceName: 'Manutenção Periódica',
    price: 220.00,
    notes: 'Limpeza e nova fixação com fita azul.',
    status: 'Agendado',
    paymentStatus: 'Pendente',
    createdAt: getRelativeDate(2),
  },
  {
    id: 'a7',
    clientId: 'c3',
    clientName: 'Felipe Augusto Melo',
    clientPhone: '(21) 99887-7665',
    date: getRelativeDate(5),
    startTime: '16:00',
    endTime: '17:30',
    serviceName: 'Manutenção Completa',
    price: 220.00,
    notes: '',
    status: 'Agendado',
    paymentStatus: 'Pendente',
    createdAt: getRelativeDate(5),
  },
];

export const SEED_TRANSACTIONS: FinancialTransaction[] = [
  // Entradas linked to appointments
  {
    id: 't1',
    type: 'Entrada',
    amount: 220.00,
    date: getRelativeDate(-15),
    description: 'Manutenção Completa (Limpeza e Recolocação) - Roberto Alves de Souza',
    appointmentId: 'a1',
    createdAt: getRelativeDate(-15),
  },
  {
    id: 't2',
    type: 'Entrada',
    amount: 250.00,
    date: getRelativeDate(-7),
    description: 'Manutenção e Hidratação de Fios - Cláudio Ferreira Lima',
    appointmentId: 'a2',
    createdAt: getRelativeDate(-7),
  },
  {
    id: 't3',
    type: 'Entrada',
    amount: 130.00,
    date: getRelativeDate(-2),
    description: 'Ajuste de Laterais e Higienização Rápida - Felipe Augusto Melo',
    appointmentId: 'a3',
    createdAt: getRelativeDate(-2),
  },
  {
    id: 't4',
    type: 'Entrada',
    amount: 240.00,
    date: getRelativeDate(0),
    description: 'Manutenção Completa com Ajuste de Corte - Roberto Alves de Souza',
    appointmentId: 'a4',
    createdAt: getRelativeDate(0),
  },
  // Saídas (Clinic expenses)
  {
    id: 't_s1',
    type: 'Saída',
    amount: 950.00,
    date: getRelativeDate(-20),
    description: 'Compra de 2 Próteses Premium Micropele (Estoque)',
    createdAt: getRelativeDate(-20),
  },
  {
    id: 't_s2',
    type: 'Saída',
    amount: 180.00,
    date: getRelativeDate(-10),
    description: 'Kit de Fitass Adesivas Ultra Hold + Removedores Solvente C-22',
    createdAt: getRelativeDate(-10),
  },
  {
    id: 't_s3',
    type: 'Saída',
    amount: 150.00,
    date: getRelativeDate(-5),
    description: 'Mensalidade do Software de Gestão e Internet da Clínica',
    createdAt: getRelativeDate(-5),
  },
  {
    id: 't_s4',
    type: 'Saída',
    amount: 80.00,
    date: getRelativeDate(0),
    description: 'Toalhas descartáveis e materiais de proteção higiênica',
    createdAt: getRelativeDate(0),
  },
];

export const SEED_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat1',
    name: 'Colocação',
    description: 'Primeira aplicação e assentamento de próteses capilares',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'cat2',
    name: 'Manutenção',
    description: 'Serviços de higienização, re-colagem, ajustes e corte',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'cat3',
    name: 'Tratamentos',
    description: 'Hidratação profunda, revitalização e cuidados especiais com os fios',
    createdAt: getRelativeDate(-30),
  },
];

export const SEED_SERVICES: Service[] = [
  {
    id: 'srv1',
    name: 'Primeira Colocação de Prótese Premium',
    categoryId: 'cat1',
    price: 1200.00,
    durationMinutes: 120,
    description: 'Colocação de prótese capilar sob medida com corte de integração e finalização.',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'srv2',
    name: 'Manutenção Completa (Limpeza e Recolocação)',
    categoryId: 'cat2',
    price: 220.00,
    durationMinutes: 90,
    description: 'Remoção, higienização completa do couro cabeludo e da peça, nova aplicação com cola/fita.',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'srv3',
    name: 'Manutenção Completa com Ajuste de Corte',
    categoryId: 'cat2',
    price: 240.00,
    durationMinutes: 90,
    description: 'Manutenção completa mais corte de igualação das laterais naturais.',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'srv4',
    name: 'Manutenção e Hidratação de Fios',
    categoryId: 'cat3',
    price: 250.00,
    durationMinutes: 90,
    description: 'Serviço de manutenção regular acrescido de máscara reconstrutora profunda.',
    createdAt: getRelativeDate(-30),
  },
  {
    id: 'srv5',
    name: 'Ajuste de Laterais e Higienização Rápida',
    categoryId: 'cat2',
    price: 130.00,
    durationMinutes: 60,
    description: 'Retoque rápido de descolamento de bordas com limpeza superficial.',
    createdAt: getRelativeDate(-30),
  },
];

